[package]
name = "rille-engine"
description = "Realtime audio engine for rille"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
assert_no_alloc = "1.1"
cpal = "0.18"
rille-core.workspace = true
rtrb = "0.4"
signalsmith-stretch = "0.1"
thiserror = "2"
triple_buffer = "9"

[lints]
workspace = true

[dev-dependencies]
assert_no_alloc = { version = "1.1", features = ["warn_debug"] }
