// Generates the colour part of the design tokens from one seed colour plus one accent seed per
// deck. Output: src/design/color.generated.css (dark is the default, light behind data-theme).
// Run with `pnpm tokens` after changing a seed. The file is committed; never edit it by hand.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  Hct,
  MaterialDynamicColors as M,
  SchemeTonalSpot,
  SchemeVibrant,
  TonalPalette,
  argbFromHex,
  hexFromArgb,
} from '@material/material-color-utilities';

export const SEEDS = {
  base: '#5b4bff',
  deckA: '#00c2d1',
  deckB: '#ff7a1a',
};

const SPEC = '2025';

const BASE_ROLES = {
  surface: M.surface,
  'surface-dim': M.surfaceDim,
  'surface-bright': M.surfaceBright,
  'surface-container-lowest': M.surfaceContainerLowest,
  'surface-container-low': M.surfaceContainerLow,
  'surface-container': M.surfaceContainer,
  'surface-container-high': M.surfaceContainerHigh,
  'surface-container-highest': M.surfaceContainerHighest,
  'on-surface': M.onSurface,
  'on-surface-variant': M.onSurfaceVariant,
  outline: M.outline,
  'outline-variant': M.outlineVariant,
  'inverse-surface': M.inverseSurface,
  'inverse-on-surface': M.inverseOnSurface,
  primary: M.primary,
  'on-primary': M.onPrimary,
  'primary-container': M.primaryContainer,
  'on-primary-container': M.onPrimaryContainer,
  secondary: M.secondary,
  'on-secondary': M.onSecondary,
  'secondary-container': M.secondaryContainer,
  'on-secondary-container': M.onSecondaryContainer,
  tertiary: M.tertiary,
  'on-tertiary': M.onTertiary,
  'tertiary-container': M.tertiaryContainer,
  'on-tertiary-container': M.onTertiaryContainer,
  error: M.error,
  'on-error': M.onError,
  'error-container': M.errorContainer,
  'on-error-container': M.onErrorContainer,
  scrim: M.scrim,
};

const DECK_ROLES = {
  '': M.primary,
  on: M.onPrimary,
  container: M.primaryContainer,
  'on-container': M.onPrimaryContainer,
};

/** Returns `{ name: '#rrggbb' }` for one theme. */
export function buildTheme(seeds, isDark) {
  const out = {};
  const base = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seeds.base)), isDark, 0, SPEC);
  for (const [name, role] of Object.entries(BASE_ROLES)) {
    out[`md-${name}`] = hexFromArgb(role.getArgb(base));
  }
  for (const [deck, seed] of [
    ['a', seeds.deckA],
    ['b', seeds.deckB],
  ]) {
    const hct = Hct.fromInt(argbFromHex(seed));
    const scheme = new SchemeVibrant(hct, isDark, 0, SPEC);
    for (const [suffix, role] of Object.entries(DECK_ROLES)) {
      out[suffix ? `deck-${deck}-${suffix}` : `deck-${deck}`] = hexFromArgb(role.getArgb(scheme));
    }
    // Waveform bands in the deck hue: low = deep, mid = deck tone, high = bright.
    const band = TonalPalette.fromHueAndChroma(hct.hue, Math.max(hct.chroma, 48));
    const [low, mid, high] = isDark ? [45, 70, 92] : [30, 50, 75];
    out[`deck-${deck}-wave-low`] = hexFromArgb(band.tone(low));
    out[`deck-${deck}-wave-mid`] = hexFromArgb(band.tone(mid));
    out[`deck-${deck}-wave-high`] = hexFromArgb(band.tone(high));
  }
  return out;
}

export function toCss(seeds) {
  const block = (selector, theme) =>
    `${selector} {\n${Object.entries(theme)
      .map(([k, v]) => `  --${k}: ${v};`)
      .join('\n')}\n}\n`;
  return (
    `/* Generated by scripts/gen-tokens.mjs from seeds ${JSON.stringify(seeds)}. Do not edit. */\n\n` +
    block(':root,\n:root[data-theme="dark"]', buildTheme(seeds, true)) +
    '\n' +
    block(':root[data-theme="light"]', buildTheme(seeds, false))
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const target = new URL('../src/design/color.generated.css', import.meta.url);
  writeFileSync(target, toCss(SEEDS));
  console.log(`wrote ${fileURLToPath(target)}`);
}
